<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Summary</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        h2   { margin-bottom: 2px; }
        .section-title { font-weight: bold; margin-top: 18px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #999; padding: 6px; text-align: left; }
    </style>
</head>
<body>

    <h2>POLYCOOL CONSTRUCTION SERVICES</h2>
    <p><em>via PolySync Management System</em></p>

    <h3>Project Payment Summary</h3>
    <p><strong>Project:</strong> {{ $project->project_name }}</p>
    <p><strong>Client:</strong> {{ $project->client->name }}</p>

    <div class="section-title">Financial Overview</div>
    <p>Base Contract Price: {{ number_format($baseContract, 2) }}</p>
    <p>Extra Work Total: {{ number_format($extraTotal, 2) }}</p>
    <p><strong>Total Project Price:</strong> {{ number_format($totalProject, 2) }}</p>
    <p>Total Paid: {{ number_format($totalPaid, 2) }}</p>
    <p><strong>Remaining Balance:</strong> {{ number_format($remaining, 2) }}</p>

    <div class="section-title">Payments Detail</div>
    <table>
        <thead>
            <tr>
                <th>Amount</th>
                <th>Method</th>
                <th>Status</th>
                <th>Date</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
        @foreach($payments as $pay)
            <tr>
                <td>{{ number_format($pay->amount, 2) }}</td>
                <td>{{ ucfirst($pay->payment_method) }}</td>
                <td>{{ ucfirst($pay->status) }}</td>
                <td>{{ $pay->payment_date ? \Carbon\Carbon::parse($pay->payment_date)->format('M d, Y') : '-' }}</td>
                <td>{{ $pay->notes }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <br><br>
    <p style="font-size:11px; color:#555;">
        System Generated by PolySync — No manual alterations allowed.
    </p>

</body>
</html>
