<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Reversal Audit Report</title>
    <style>
        * { font-family: Arial, sans-serif; }
        body { font-size: 12px; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; font-size: 11px; }
        th { background: #f7f7f7; font-weight: bold; }
        .title-main { font-size: 18px; font-weight: bold; text-align: center; margin-bottom: 2px; }
        .subtitle { font-size: 11px; text-align: center; color: #444; margin-bottom: 20px; }
        .section-title { font-weight: bold; margin: 10px 0 4px; }
        .footer { font-size: 9px; text-align: center; margin-top: 30px; color: #777; }
    </style>
</head>
<body>

    {{-- HEADER --}}
    <div class="title-main">POLYCOOL CONSTRUCTION SERVICES</div>
    <div class="subtitle">via PolySync Management System</div>

    {{-- PROJECT & FINANCIAL SNAPSHOT --}}
    <p class="section-title">Project Information</p>
    <table>
        <tr>
            <th>Project Name</th>
            <td>{{ $payment->project->name }}</td>
        </tr>
        <tr>
            <th>Client</th>
            <td>{{ $payment->project->client->name }}</td>
        </tr>
        <tr>
            <th>Total Project Price</th>
            <td>₱{{ number_format($payment->project->total_price ?? 0, 2) }}</td>
        </tr>
        <tr>
            <th>Total Paid Before This Reversal</th>
            <td>₱{{ number_format($payment->project->payments()->where('status','approved')->sum('amount'), 2) }}</td>
        </tr>
        <tr>
            <th>Remaining Balance</th>
            <td>₱{{ number_format(($payment->project->total_price ?? 0)
                - $payment->project->payments()->where('status','approved')->sum('amount'), 2) }}</td>
        </tr>
    </table>

    {{-- ORIGINAL PAYMENT --}}
    <p class="section-title">Original Payment</p>
    <table>
        <tr><th>Amount</th>
            <td>
                @if($original)
                    ₱{{ number_format($original->amount, 2) }}
                @else
                    —
                @endif
            </td>
        </tr>
        <tr><th>Payment Method</th><td>{{ $original->payment_method ?? '—' }}</td></tr>
        <tr><th>Date</th><td>{{ $original?->payment_date ?? '—' }}</td></tr>
        <tr><th>Cancelled By</th><td>{{ $original?->canceller->name ?? '—' }}</td></tr>
        <tr><th>Cancel Reason</th><td>{{ $original?->cancel_reason ?? '—' }}</td></tr>
        <tr><th>Cancelled At</th><td>{{ $original?->updated_at ?? '—' }}</td></tr>
    </table>

    {{-- REPLACEMENT PAYMENT --}}
    <p class="section-title">Replacement Payment</p>
    <table>
        <tr><th>Amount</th>
            <td>
                @if($replaced)
                    {{ number_format($replaced->amount, 2) }}
                @else
                    Not yet issued
                @endif
            </td>
        </tr>
        <tr><th>Payment Method</th><td>{{ $replaced?->payment_method ?? '—' }}</td></tr>
        <tr><th>Date</th><td>{{ $replaced?->payment_date ?? '—' }}</td></tr>
        <tr><th>Corrected By</th><td>{{ $replaced?->submitter?->name ?? '—' }}</td></tr>
        <tr><th>Correction Notes</th><td>{{ $replaced?->correction_reason ?? '—' }}</td></tr>
        <tr><th>Re-Issued At</th><td>{{ $replaced?->updated_at ?? '—' }}</td></tr>
    </table>

    <div class="footer">
        System Generated by PolySync — No manual alterations allowed.
    </div>

</body>
</html>
