<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; font-size: 13px; }
        .title { font-size: 20px; font-weight: bold; margin-bottom: 10px; }
        .section { margin-bottom: 12px; }
        .label { color: #555; }
        .value { font-weight: bold; }
        hr { margin: 10px 0; }
    </style>
</head>
<body>

<div class="title">Payment Report</div>

<div class="section">
    <div class="label">Project:</div>
    <div class="value">{{ $payment->project->project_name }}</div>
</div>

<div class="section">
    <div class="label">Amount:</div>
    <div class="value">₱{{ number_format($payment->amount, 2) }}</div>
</div>

<div class="section">
    <div class="label">Payment Method:</div>
    <div class="value">{{ ucfirst($payment->payment_method) }}</div>
</div>

<div class="section">
    <div class="label">Date:</div>
    <div class="value">{{ \Carbon\Carbon::parse($payment->payment_date)->format('F d, Y') }}</div>
</div>

<div class="section">
    <div class="label">Status:</div>
    <div class="value">{{ ucfirst($payment->status) }}</div>
</div>

<div class="section">
    <div class="label">Added By:</div>
    <div class="value">{{ $payment->addedBy->full_name }}</div>
</div>

<div class="section">
    <div class="label">Approved By:</div>
    <div class="value">{{ $payment->approvedBy->full_name ?? '—' }}</div>
</div>

<hr>
<p style="text-align:center;">Generated by PolySync — {{ now()->format('F d, Y h:i A') }}</p>

</body>
</html>
