<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $quotation->reference }}</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        h2 {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            padding: 8px;
            border: 1px solid #999;
        }
        th {
            background: #f3f3f3;
        }
        .text-right {
            text-align: right;
        }
        .section-title {
            font-weight: bold;
            margin-top: 25px;
            margin-bottom: 8px;
            font-size: 14px;
        }
        .info-table td {
            border: none;
            padding: 4px 0;
        }
        .footer {
            margin-top: 40px;
            font-size: 11px;
            text-align: center;
        }
        .signature-box {
            margin-top: 60px;
        }
        .signature-line {
            border-top: 1px solid #000;
            width: 250px;
            margin-top: 40px;
        }
    </style>
</head>

<body>

    {{-- HEADER --}}
    <div class="header">
        <h2><strong>POLYCOOL INSULATION SERVICES</strong></h2>
        <p>Official Quotation Document</p>
    </div>

    {{-- BASIC INFO --}}
    <table class="info-table">
        <tr>
            <td><strong>Reference:</strong> {{ $quotation->reference }}</td>
            <td><strong>Date:</strong> {{ $quotation->created_at->format('M d, Y') }}</td>
        </tr>
        <tr>
            <td><strong>Client:</strong> {{ $quotation->client->name ?? '—' }}</td>
            <td><strong>Valid Until:</strong>
                {{ $quotation->valid_until ? $quotation->valid_until->format('M d, Y') : '—' }}
            </td>
        </tr>
        <tr>
            <td colspan="2"><strong>Project Title:</strong> {{ $quotation->title }}</td>
        </tr>
    </table>

    {{-- DESCRIPTION --}}
    @if($quotation->description)
        <div class="section-title">Project Description</div>
        <p style="white-space: pre-line;">
            {{ $quotation->description }}
        </p>
    @endif

    {{-- ITEMS TABLE --}}
    <div class="section-title">Quotation Items</div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th>Unit</th>
                <th class="text-right">Qty</th>
                <th class="text-right">Unit Price</th>
                <th class="text-right">Line Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($quotation->items as $item)
                <tr>
                    <td>{{ $item->description }}</td>
                    <td>{{ $item->unit }}</td>
                    <td class="text-right">{{ number_format($item->quantity, 2) }}</td>
                    <td class="text-right">₱{{ number_format($item->unit_price, 2) }}</td>
                    <td class="text-right">₱{{ number_format($item->line_total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{-- TOTALS --}}
    <div class="section-title">Summary</div>

    <table style="width: 50%; margin-left: auto;">
        <tr>
            <td><strong>Subtotal:</strong></td>
            <td class="text-right">₱{{ number_format($quotation->subtotal, 2) }}</td>
        </tr>
        <tr>
            <td><strong>Tax ({{ $quotation->tax_rate }}%):</strong></td>
            <td class="text-right">₱{{ number_format($quotation->tax_amount, 2) }}</td>
        </tr>
        <tr>
            <td><strong>Discount:</strong></td>
            <td class="text-right">₱{{ number_format($quotation->discount_amount, 2) }}</td>
        </tr>
        <tr>
            <td><strong>Total Amount:</strong></td>
            <td class="text-right"><strong>₱{{ number_format($quotation->total_amount, 2) }}</strong></td>
        </tr>
    </table>

    {{-- SIGNATURE --}}
    <div class="signature-box">
        <p>Prepared by:</p>
        <div class="signature-line"></div>
        <p>{{ $quotation->user->name ?? '—' }}</p>

        @if($quotation->approver)
            <br><br>
            <p>Approved by:</p>
            <div class="signature-line"></div>
            <p>{{ $quotation->approver->name }}</p>
        @endif
    </div>

    {{-- FOOTER --}}
    <div class="footer">
        <p>This is an official quotation generated by PolySync System.</p>
        <p>Prices above may vary depending on actual site conditions.</p>
    </div>

</body>
</html>
